### ISSUE TITLE
Snake shape payload plan

### ISSUE THREAD

**Issue by avaly** [balboah/flow#3]
How do you plan to format the payload for the clients regarding the shape of a snake? I'd like to work on this, but need to know how the data will come from the server.

I see at least two options. For example, if you have this snake (T is the head):

```
..T...
..xxxx
.....x
....xx
```
1. Send the full snake shape in each payload:
   
   `['id', [2,1], [2,2], [2,6], [4,6], [4,5]]`
2. Send the full snake shape on first message for each snake, and all subsequent messages contain only the direction, thus forcing the clients to track the snake shape:
   
   `['id', 'N']`

**Comment by balboah** [comment]
I was thinking about this.
What do you think of the [wiki example](https://github.com/balboah/flow/wiki)?

**Comment by avaly** [comment]
Yeah, I like the wiki specs. It's a bit more clear than a simple array. I'll get something written based on that structure.

**Comment by balboah** [comment]
Feel free to modify the wiki while you're doing some tests
